---
title: Broadcasting Examples
tags: [jupyter]
keywords: course, coursera, deepLearningAI
summary: "Looking at some examples for broadcasting in python"
sidebar: coursera_sidebar
permalink: __AutoGenThis__
notebookfilename:  __AutoGenThis__
---

![](broadcastingExample)

In [1]:
import numpy as np

In [6]:
A = np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
            [1.8,135.0,99.0,0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [8]:
cal = np.sum(A,axis=0)
print(cal)

[ 59.  239.  155.4  76.9]


In [11]:
percentages = 100*A/cal
print(percentages)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


The above is the same as using the reshape() function to ensure that the divident is actually the same shape that you really want it to be

In [12]:
percentages = 100*A/cal.reshape(1,4)
print(percentages)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Weaknesses and Strange Effects

In [23]:
a = np.random.randn(5)
print(a)

[ 0.46844939 -2.00466499  1.22319756  0.20679197 -1.23257532]


In [15]:
a.shape

(5,)

This 5, is called a rank 1 array and is not either a row or column arrays

In [16]:
print(a.T)

[0.38431345 0.85353119 2.12900563 1.4322792  0.0241802 ]


In [17]:
print(np.dot(a,a.T))

7.460885700088016


The above should give you a matrix of the outer product of the vector a.  But it gives you a single value.  This is one of the bugs that can arise when broadcasting in python.  **When you are coding you should avoid having this rank one arrays**.

You can also apply **assert** statements like

```python
assert(a.shape == (5,1))
```

for documentation purposes and also make sure everything is properly shaped.

In [21]:
a = np.random.randn(5,1)
print(a.T)
print('\n')
print(np.dot(a,a.T))

[[-1.43277431 -1.3949054   0.6119326  -0.0618812  -1.09517802]]


[[ 2.05284223  1.99858462 -0.8767613   0.0886618   1.56914294]
 [ 1.99858462  1.94576107 -0.85358808  0.08631842  1.52766973]
 [-0.8767613  -0.85358808  0.3744615  -0.03786712 -0.67017513]
 [ 0.0886618   0.08631842 -0.03786712  0.00382928  0.06777093]
 [ 1.56914294  1.52766973 -0.67017513  0.06777093  1.1994149 ]]


In [24]:
assert(a.shape == (5,1))

AssertionError: 

This is a quick fix when a assert is triggered.

In [25]:
a = a.reshape(5,1)