---
title: Sortin - Numpy vs Python
tags: [jupyter]
keywords: numpy
summary: "Looking at numpy sorting."
mlType: dataFrame
infoType: numpy
sidebar: numpy_sidebar
permalink: __AutoGenThis__
notebookfilename:  __AutoGenThis__
---

This was taken from [Sorting](https://jakevdp.github.io/PythonDataScienceHandbook/02.08-sorting.html) from the [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html)

In [1]:
import numpy as np

# Fast sorting np.sort() and np.argsort()

**np.sort()** returns a sorted array while

**np.argsort()** returns the indices of the sorted array

## 1D

In [3]:
x = np.random.randint(1,20,10)
x

array([10, 10, 10, 10,  7,  9, 16, 10, 12, 10])

In [4]:
np.sort(x)

array([ 7,  9, 10, 10, 10, 10, 10, 10, 12, 16])

In [5]:
np.argsort(x)

array([4, 5, 0, 1, 2, 3, 7, 9, 8, 6], dtype=int64)

## 2D

In [6]:
y = np.random.randint(3,50,10)
z = np.random.randint(6,20,10)
w = np.vstack([x,y,z])
w

array([[10, 10, 10, 10,  7,  9, 16, 10, 12, 10],
       [49, 12,  7, 21, 22, 21, 48, 32, 18, 45],
       [10, 18,  7, 15, 13, 18, 19, 13, 12, 19]])

### Coloumn wise sort

In [7]:
np.sort(w,axis=0)

array([[10, 10,  7, 10,  7,  9, 16, 10, 12, 10],
       [10, 12,  7, 15, 13, 18, 19, 13, 12, 19],
       [49, 18, 10, 21, 22, 21, 48, 32, 18, 45]])

### Row wise sort

In [8]:
np.sort(w,axis=1)

array([[ 7,  9, 10, 10, 10, 10, 10, 10, 12, 16],
       [ 7, 12, 18, 21, 21, 22, 32, 45, 48, 49],
       [ 7, 10, 12, 13, 13, 15, 18, 18, 19, 19]])