---
title: Universal Functions - Numpy vs Python
tags: [jupyter]
keywords: numpy
summary: "Looking at numpy universal functions."
mlType: dataFrame
infoType: numpy
sidebar: numpy_sidebar
permalink: __AutoGenThis__
notebookfilename:  __AutoGenThis__
---

This was taken from [Universal Functions](https://jakevdp.github.io/PythonDataScienceHandbook/02.03-computation-on-arrays-ufuncs.html) from the [Python Data Science Handbook](https://jakevdp.github.io/PythonDataScienceHandbook/index.html)

The functions listed here are more efficient that the normal python implementation because they run C type python.  THe book calls there cpython implementation.

In [1]:
import numpy as np

# Basic Math Operators

![](https://drive.google.com/uc?id=12jrhNHad2ECjz2HZY_csN3RHDDGv9PYb)

# Math Function Operators

![](https://drive.google.com/uc?id=1XNR2_oU_-WG7i3-kTWQnaHSvVR24poLd)

# Boolean Functions Operators

![](https://drive.google.com/uc?id=1HpxzF6JnElZ8fMK3qCA13dqQgqInBpJU)

These return an array of boolean values based on the operation

In [3]:
x = np.array([1, 2, 3, 4, 5])

In [4]:
x < 3

array([ True,  True, False, False, False])

![](https://drive.google.com/uc?id=1Dut-gDxJ6ObXKcO3tEDIskoMuiVYQt_T)

In [8]:
x

array([1, 2, 3, 4, 5])

In [9]:
(x < 3) & (x>1)

array([False,  True, False, False, False])

ONly one is true which is the index for 2